/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface GmonadWallInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "COOLDOWN"
      | "MAX_LENGTH"
      | "MAX_READ"
      | "getCooldownRemaining"
      | "getLatestMessages"
      | "getMessageCount"
      | "hideMessage"
      | "owner"
      | "postMessage"
      | "renounceOwnership"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "MessageHidden"
      | "MessagePosted"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(functionFragment: "COOLDOWN", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "MAX_LENGTH",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "MAX_READ", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getCooldownRemaining",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getLatestMessages",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMessageCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "hideMessage",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "postMessage", values: [string]): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "COOLDOWN", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "MAX_LENGTH", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "MAX_READ", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getCooldownRemaining",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLatestMessages",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMessageCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hideMessage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "postMessage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace MessageHiddenEvent {
  export type InputTuple = [id: BigNumberish, hidden: boolean];
  export type OutputTuple = [id: bigint, hidden: boolean];
  export interface OutputObject {
    id: bigint;
    hidden: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MessagePostedEvent {
  export type InputTuple = [
    id: BigNumberish,
    author: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [id: bigint, author: string, timestamp: bigint];
  export interface OutputObject {
    id: bigint;
    author: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface GmonadWall extends BaseContract {
  connect(runner?: ContractRunner | null): GmonadWall;
  waitForDeployment(): Promise<this>;

  interface: GmonadWallInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  COOLDOWN: TypedContractMethod<[], [bigint], "view">;

  MAX_LENGTH: TypedContractMethod<[], [bigint], "view">;

  MAX_READ: TypedContractMethod<[], [bigint], "view">;

  getCooldownRemaining: TypedContractMethod<
    [user: AddressLike],
    [bigint],
    "view"
  >;

  getLatestMessages: TypedContractMethod<
    [limit: BigNumberish],
    [
      [bigint[], string[], bigint[], boolean[]] & {
        ids: bigint[];
        texts: string[];
        timestamps: bigint[];
        hiddenFlags: boolean[];
      }
    ],
    "view"
  >;

  getMessageCount: TypedContractMethod<[], [bigint], "view">;

  hideMessage: TypedContractMethod<
    [id: BigNumberish, hidden: boolean],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  postMessage: TypedContractMethod<[text: string], [void], "nonpayable">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "COOLDOWN"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_LENGTH"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_READ"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getCooldownRemaining"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getLatestMessages"
  ): TypedContractMethod<
    [limit: BigNumberish],
    [
      [bigint[], string[], bigint[], boolean[]] & {
        ids: bigint[];
        texts: string[];
        timestamps: bigint[];
        hiddenFlags: boolean[];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMessageCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "hideMessage"
  ): TypedContractMethod<
    [id: BigNumberish, hidden: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "postMessage"
  ): TypedContractMethod<[text: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "MessageHidden"
  ): TypedContractEvent<
    MessageHiddenEvent.InputTuple,
    MessageHiddenEvent.OutputTuple,
    MessageHiddenEvent.OutputObject
  >;
  getEvent(
    key: "MessagePosted"
  ): TypedContractEvent<
    MessagePostedEvent.InputTuple,
    MessagePostedEvent.OutputTuple,
    MessagePostedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "MessageHidden(uint256,bool)": TypedContractEvent<
      MessageHiddenEvent.InputTuple,
      MessageHiddenEvent.OutputTuple,
      MessageHiddenEvent.OutputObject
    >;
    MessageHidden: TypedContractEvent<
      MessageHiddenEvent.InputTuple,
      MessageHiddenEvent.OutputTuple,
      MessageHiddenEvent.OutputObject
    >;

    "MessagePosted(uint256,address,uint256)": TypedContractEvent<
      MessagePostedEvent.InputTuple,
      MessagePostedEvent.OutputTuple,
      MessagePostedEvent.OutputObject
    >;
    MessagePosted: TypedContractEvent<
      MessagePostedEvent.InputTuple,
      MessagePostedEvent.OutputTuple,
      MessagePostedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
